global using Carter;
global using MediatR;
global using BuildingBlocks.CQRS;
global using FluentValidation;
global using Marten;
global using Mapster;
global using Auth.API.Enums;
global using model = Auth.API.Models;
global using Auth.API.Exceptions;
global using Marten.Pagination;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Auth.API.Dtos;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.Extensions.Caching.Distributed;
global using Auth.API.Auth.Token;