version: '3.4'

x-postgres-creds: &postgres-creds
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-aspnet-env: &aspnet-env
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: 8080
  ASPNETCORE_HTTPS_PORTS: 8081
  ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
  ASPNETCORE_Kestrel__Certificates__Default__Password: 1234

x-https-volumes: &https-volumes
  - ${USERPROFILE}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  - ${USERPROFILE}/ASP.NET/Https:/https:ro

services:
  catalogdb:
    container_name: catalogdb
    environment:
      <<: *postgres-creds
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  basketdb:
    container_name: basketdb
    environment:
      <<: *postgres-creds
      POSTGRES_DB: BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  authdb:
    container_name: authdb
    environment:
      <<: *postgres-creds
      POSTGRES_DB: AuthDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth:/var/lib/postgresql/data

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin123456!
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    container_name: Catalog.API
    environment:
      <<: *aspnet-env
      ConnectionStrings__Database: Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes: *https-volumes

  basket.api:
    container_name: Basket.API
    environment:
      <<: *aspnet-env
      ConnectionStrings__Database: Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      ConnectionStrings__Redis: distributedcache:6379
      GrpcSettings__DiscountUrl: https://discount.grpc:8081
      MessageBroker__Host: amqp://ecommerce-mq:5672
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker 
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes: *https-volumes

  discount.grpc:
    container_name: Discount.Grpc
    environment:
      <<: *aspnet-env
      ConnectionStrings__Database: Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes: *https-volumes

  ordering.api:
    container_name: Ordering.API
    environment:
      <<: *aspnet-env
      ConnectionStrings__Database: Server=orderdb;Database=OrderDb;User Id=sa;Password=Admin123456!;Encrypt=False;TrustServerCertificate=True
      MessageBroker__Host: amqp://ecommerce-mq:5672
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
      FeatureManagement__OrderFullfilment: "false"
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes: *https-volumes

  yarpapigateway:
    container_name: YarpApiGateway
    environment:
      <<: *aspnet-env
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes: *https-volumes

  shopping.web:
    container_name: Shopping.Web
    environment:
      <<: *aspnet-env
      ApiSettings__GatewayAddress: http://yarpapigateway:8080
    depends_on:
      - yarpapigateway
    ports:
      - "6005:8080"
      - "6065:8081"
    volumes: *https-volumes

  auth.api:
    container_name: Auth.API
    environment:
      <<: *aspnet-env
      ConnectionStrings__Database: Server=authdb;Port=5432;Database=AuthDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - authdb
    ports:
      - "6006:8080"
      - "6066:8081"
    volumes: *https-volumes

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_auth:
